services:
  - type: web
    name: bank-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py shell < create_superuser.py
    startCommand: gunicorn Bank.wsgi
