# Generated by Django 3.2.25 on 2025-09-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(max_length=20)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('branch', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('town_city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('account_created_on', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
    ]
